# Site settings
title: Willololo's Blog
SEOTitle: 薇洛洛的博客 | Willololo's Blog
header-img: img/post-bg-garden.png
email: 这里缺一个邮箱
description: "2d Animation Artist"
keyword: "Willololo, Willololo's Blog, 薇洛洛的博客, 薇洛洛"
url: "https://Willololo7.github.io/"           # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: https://github.com/Willololo7/Willololo7.github.io # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "The focused mind can pierce through stone."
sidebar-avatar: /img/HeadIcon.png      # use absolute URL, seeing it's used in both `/` and `/about/`
future: true



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     薇洛洛Willololo
github_username:    Willololo7
bilibili_username:  Willololo
jianshu_username:  
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: WillololoPeng7

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: Ov23lijoyN89AwtzcS8n                            #生成的clientID
  clientSecret: 516e7e76f24b103b34a421cedeca8c50e4b13e00    #生成的clientSecret
  repo: Willololo7.github.io    #仓库名称
  owner: Willololo7    #github用户名
  admin: Willololo7
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    # {
    #     title: "WY",
    #     href: "http://zhengwuyang.com"
    # },{
    #     title: "Bilibili",
    #     href: "https://space.bilibili.com/606572628?spm_id_from=333.934.0.0"
    # },{
    #     title: "Apple",
    #     href: "https://apple.com"
    # },{
    #     title: "Apple Developer",
    #     href: "https://developer.apple.com/"
    # }
]
